In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("your_cleaned_dataset.csv")

df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'your_cleaned_dataset.csv'

In [2]:
import os

print(os.listdir())

['EDA.ipynb', 'Feature engineering.ipynb', 'ijzp-q8t2.csv', 'patrol cleaned data.ipynb', 'PatrolIQ_cleaned.csv']

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("PatrolIQ_cleaned.csv")

print(df.shape)
df.head()

(500000, 22)

,id,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,14299731,JK380653,2026-08-19 00:00:00,040XX W 115TH ST,0820,THEFT,$500 AND UNDER,APARTMENT,False,False,...,19.0,74.0,06,1151309.0,1828012.0,2026,2026-08-26 15:42:45,41.683938,-87.721741,"(41.683938235, -87.721741177)"
1,14300471,JK381485,2026-08-19 00:00:00,005XX N LAKE SHORE DR,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,OTHER (SPECIFY),False,False,...,42.0,8.0,26,1180411.0,1903950.0,2026,2026-08-26 15:42:45,41.891703,-87.612879,"(41.891702907, -87.612878748)"
2,14299663,JK380430,2026-08-19 00:00:00,057XX S DR MARTIN LUTHER KING JR DR,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,20.0,40.0,08B,1179905.0,1866989.0,2026,2026-08-26 15:42:45,41.790291,-87.615871,"(41.790291029, -87.615870924)"
3,14298460,JK378934,2026-08-19 00:00:00,003XX W KINZIE ST,0620,BURGLARY,UNLAWFUL ENTRY,OTHER (SPECIFY),False,False,...,42.0,8.0,05,1173758.0,1902956.0,2026,2026-08-26 15:42:45,41.889126,-87.637342,"(41.889126004, -87.637341538)"
4,14298408,JK378893,2026-08-19 00:00:00,081XX S EVANS AVE,0610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,...,6.0,44.0,05,1182641.0,1851209.0,2026,2026-08-26 15:42:45,41.746926,-87.606328,"(41.746926074, -87.606327923)"

In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv("PatrolIQ_cleaned.csv")

print(df.shape)
df.head()

(500000, 22)

,id,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,14299731,JK380653,2026-08-19 00:00:00,040XX W 115TH ST,0820,THEFT,$500 AND UNDER,APARTMENT,False,False,...,19.0,74.0,06,1151309.0,1828012.0,2026,2026-08-26 15:42:45,41.683938,-87.721741,"(41.683938235, -87.721741177)"
1,14300471,JK381485,2026-08-19 00:00:00,005XX N LAKE SHORE DR,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,OTHER (SPECIFY),False,False,...,42.0,8.0,26,1180411.0,1903950.0,2026,2026-08-26 15:42:45,41.891703,-87.612879,"(41.891702907, -87.612878748)"
2,14299663,JK380430,2026-08-19 00:00:00,057XX S DR MARTIN LUTHER KING JR DR,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,20.0,40.0,08B,1179905.0,1866989.0,2026,2026-08-26 15:42:45,41.790291,-87.615871,"(41.790291029, -87.615870924)"
3,14298460,JK378934,2026-08-19 00:00:00,003XX W KINZIE ST,0620,BURGLARY,UNLAWFUL ENTRY,OTHER (SPECIFY),False,False,...,42.0,8.0,05,1173758.0,1902956.0,2026,2026-08-26 15:42:45,41.889126,-87.637342,"(41.889126004, -87.637341538)"
4,14298408,JK378893,2026-08-19 00:00:00,081XX S EVANS AVE,0610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,...,6.0,44.0,05,1182641.0,1851209.0,2026,2026-08-26 15:42:45,41.746926,-87.606328,"(41.746926074, -87.606327923)"

In [5]:
print(df.columns.tolist())

['id', 'case_number', 'date', 'block', 'iucr', 'primary_type', 'description', 'location_description', 'arrest', 'domestic', 'beat', 'district', 'ward', 'community_area', 'fbi_code', 'x_coordinate', 'y_coordinate', 'year', 'updated_on', 'latitude', 'longitude', 'location']

In [6]:
# ==========================================
# FEATURE ENGINEERING 1 - TEMPORAL FEATURES
# ==========================================

# Convert date to datetime
df["date"] = pd.to_datetime(df["date"], errors="coerce")

# Create temporal features
df["hour"] = df["date"].dt.hour
df["day_of_week"] = df["date"].dt.day_name()
df["month"] = df["date"].dt.month

# Weekend flag
df["is_weekend"] = df["day_of_week"].isin(
    ["Saturday", "Sunday"]
)

# Season
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Fall"

df["season"] = df["month"].apply(get_season)

print(df[
    ["date", "hour", "day_of_week", "month",
     "is_weekend", "season"]
].head())

        date  hour day_of_week  month  is_weekend  season
0 2026-08-19     0   Wednesday      8       False  Summer
1 2026-08-19     0   Wednesday      8       False  Summer
2 2026-08-19     0   Wednesday      8       False  Summer
3 2026-08-19     0   Wednesday      8       False  Summer
4 2026-08-19     0   Wednesday      8       False  Summer

In [7]:
# ==========================================
# FEATURE ENGINEERING 2 - CRIME SEVERITY
# ==========================================

severity_map = {
    "NON-CRIMINAL": 1,
    "THEFT": 2,
    "DECEPTIVE PRACTICE": 2,
    "NARCOTICS": 3,
    "BURGLARY": 3,
    "CRIMINAL DAMAGE": 3,
    "CRIMINAL TRESPASS": 3,
    "MOTOR VEHICLE THEFT": 3,
    "ASSAULT": 4,
    "BATTERY": 4,
    "ROBBERY": 4,
    "WEAPONS VIOLATION": 4,
    "HOMICIDE": 5,
    "KIDNAPPING": 5,
    "CRIMINAL SEXUAL ASSAULT": 5,
    "HUMAN TRAFFICKING": 5
}

df["crime_severity_score"] = (
    df["primary_type"]
    .map(severity_map)
    .fillna(2)
)

print(df[["primary_type", "crime_severity_score"]].head())

    primary_type  crime_severity_score
0          THEFT                   2.0
1  OTHER OFFENSE                   2.0
2        BATTERY                   4.0
3       BURGLARY                   3.0
4       BURGLARY                   3.0

In [8]:
# ==========================================
# FEATURE ENGINEERING 3 - GEOGRAPHIC FEATURES
# ==========================================

# Remove rows without coordinates
df = df.dropna(subset=["latitude", "longitude"]).copy()

# Create geographic grid
df["lat_zone"] = df["latitude"].round(2)
df["lon_zone"] = df["longitude"].round(2)

print(df[[
    "latitude",
    "longitude",
    "lat_zone",
    "lon_zone"
]].head())

print("\nShape after geographic cleaning:", df.shape)

    latitude  longitude  lat_zone  lon_zone
0  41.683938 -87.721741     41.68    -87.72
1  41.891703 -87.612879     41.89    -87.61
2  41.790291 -87.615871     41.79    -87.62
3  41.889126 -87.637342     41.89    -87.64
4  41.746926 -87.606328     41.75    -87.61

Shape after geographic cleaning: (497983, 30)

In [9]:
# ==========================================
# FEATURE ENGINEERING 4 - CATEGORICAL ENCODING
# ==========================================

# Frequency encode crime type
crime_freq = df["primary_type"].value_counts(normalize=True)
df["crime_type_freq"] = df["primary_type"].map(crime_freq)

# Frequency encode location
location_freq = df["location_description"].value_counts(normalize=True)
df["location_freq"] = df["location_description"].map(location_freq)

print(df[[
    "primary_type",
    "crime_type_freq",
    "location_description",
    "location_freq"
]].head())

    primary_type  crime_type_freq location_description  location_freq
0          THEFT         0.229044            APARTMENT       0.194539
1  OTHER OFFENSE         0.068227      OTHER (SPECIFY)       0.017234
2        BATTERY         0.180677            APARTMENT       0.194539
3       BURGLARY         0.045624      OTHER (SPECIFY)       0.017234
4       BURGLARY         0.045624            APARTMENT       0.194539

In [10]:
# ==========================================
# FEATURE ENGINEERING 5 - ML FEATURES
# ==========================================

features = [
    "latitude",
    "longitude",
    "hour",
    "month",
    "is_weekend",
    "crime_severity_score",
    "crime_type_freq",
    "location_freq",
    "district",
    "community_area"
]

X = df[features].copy()

print("ML Feature Shape:", X.shape)
print("\nFeatures:")
print(X.columns.tolist())

print("\nMissing Values:")
print(X.isna().sum())

ML Feature Shape: (497983, 10)

Features:
['latitude', 'longitude', 'hour', 'month', 'is_weekend', 'crime_severity_score', 'crime_type_freq', 'location_freq', 'district', 'community_area']

Missing Values:
latitude                 0
longitude                0
hour                     0
month                    0
is_weekend               0
crime_severity_score     0
crime_type_freq          0
location_freq            0
district                19
community_area          11
dtype: int64

In [11]:
# ==========================================
# FEATURE ENGINEERING 6 - MISSING VALUES
# ==========================================

X["district"] = X["district"].fillna(X["district"].median())
X["community_area"] = X["community_area"].fillna(
    X["community_area"].median()
)

print("Remaining Missing Values:")
print(X.isna().sum())

Remaining Missing Values:
latitude                0
longitude               0
hour                    0
month                   0
is_weekend              0
crime_severity_score    0
crime_type_freq         0
location_freq           0
district                0
community_area          0
dtype: int64

In [12]:
# ==========================================
# FEATURE ENGINEERING 7 - FEATURE SCALING
# ==========================================

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Scaled Feature Shape:", X_scaled.shape)
print("\nFirst 5 rows:")
print(X_scaled[:5])

Scaled Feature Shape: (497983, 10)

First 5 rows:
[[-1.88424971 -0.91360512 -1.8243974   0.40138481 -0.63985241 -1.10694667
   1.39048663  0.58236048  1.52490209  1.75722593]
 [ 0.52758115  0.92982323 -1.8243974   0.40138481 -0.63985241 -1.10694667
  -0.74822281 -1.09694212  0.95893046 -1.31754292]
 [-0.64965603  0.87915504 -1.8243974   0.40138481 -0.63985241  1.21424729
   0.74725008  0.58236048 -1.30495608  0.1732541 ]
 [ 0.49766724  0.51558114 -1.8243974   0.40138481 -0.63985241  0.05365031
  -1.0488236  -1.09694212  0.95893046 -1.31754292]
 [-1.153057    1.04075201 -1.8243974   0.40138481 -0.63985241  0.05365031
  -1.0488236   0.58236048 -0.73898444  0.35960372]]

In [13]:
# ==========================================
# FEATURE ENGINEERING 8 - SAVE ML DATA
# ==========================================

X.to_csv("PatrolIQ_ML_Features.csv", index=False)

print("ML-ready dataset saved successfully!")
print("Shape:", X.shape)

ML-ready dataset saved successfully!
Shape: (497983, 10)